---
- name: Render VMware VM Provisioning Template
  ansible.builtin.include_tasks: "vmware.yml"
  vars:
    vcenter_hostname: "{{ vcenter_host }}"
  loop: "{{ vcenter_hosts }}"
  loop_control:
    loop_var: vcenter_hostname
    
# - include_tasks: "f5-add-pool-member.yml"
#   vars:
#     f5_device: "{{ f5_host }}"
#   loop: "{{ f5_hosts }}"
#   loop_control:
#     loop_var: f5_host
