---
# - name: Get List of LTM-Pools
#   bigip_device_info:
#     gather_subset: ltm-pools
#     provider:
#       server: "{{ f5_device }}"
#       user: "{{ f5_user }}"
#       password: "{{ f5_password }}"
#       validate_certs: false
#   register: dev_info
#   delegate_to: localhost

- name: Render Templates
  ansible.builtin.template:
    src: "{{ template.src }}"
    dest: "{{ template.dest }}"
    mode: 0600
    force: true
  loop:
    - {src: 'f5-add-pool-member.j2', dest: 'template_surveys/F5-ADD-POOL-MEMBER-{{ f5_device }}.yml'}
    - {src: 'f5-remove-pool-member.j2', dest: 'template_surveys/F5-REMOVE-POOL-MEMBER-{{ f5_device }}.yml'}
  loop_control:
    loop_var: template
